image: cypress/base:18.6.0

pipelines:
  branches:
    master:
      - step:
          caches:
            - npm
            - node
            - cypress
          script:
            # Clean/Install dependencies
            - npm ci
            # Start the server & Run the tests
            - npm run test:ci
            # TODO: Deploy it to your hosting provider
definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress
