name: Node Continuous integration

on:
  push:
    branches:
      - master
  # pull_request:
  #  branches: [master]

jobs:
  test-run:
    runs-on: ubuntu-latest
    container: cypress/base:18.6.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clean/Install dependencies
        run: npm ci

      - name: Start the server & Run the tests
        run: npm run test:ci

      - name: Build
        run: npm run build:prod

      # TODO: Deploy it to your hosting provider
